name: push_restapi_dart
description: "Push SDK provides an abstraction layer to integrate Push protocol features with your Frontend as well as Backend."
version: 0.0.1-alpha
homepage: https://docs.push.org/developers
repository: https://github.com/ethereum-push-notification-service/push-restapi-dart


environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: ">=3.7.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  hex: ^0.2.0
  http: ^0.13.6
  pointycastle: ^3.7.3
  riverpod: ^2.3.6
  openpgp: ^3.5.4
  cryptography: ^2.5.0
  web3lib: ^2.3.5
  dart_pg: ^1.1.5


flutter:
  assets:
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm